name: build
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest # macos-latest macos-11 windows-2019 ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and Run Tests
        run: mvn -B verify # -B: --batch-mode